title: Opia World
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Opia World: https://opia-world.com
  RU: https://opia-world.github.io
